version: '3.8'

services:
  docker-ms-beer:
    build:
      context: .
    container_name: rest-server
    hostname: rest-server
    networks:
      - mynet
    ports:
      - 80:8080
    environment:
      - CURRENCY_API_KEY=${CURRENCY_API_KEY}
      - CURRENCY_API_URL=${CURRENCY_API_URL}
      - API_NAME=${API_NAME}
      - API_SERVER_HOST=${API_SERVER_HOST}
      - API_SERVER_PORT=${API_SERVER_PORT}
    deploy:
      restart_policy:
        condition: on-failure

networks:
  mynet:
    driver: bridge